### ISSUE TITLE
The tutorial of front-end is gone

### ISSUE THREAD

**Issue by master-davidlee** [substrate-developer-hub/substrate-front-end-template#105]
Why the tutorial about front-end is gone and also the docs?

**Comment by danforbes** [comment]
Closing in favor of https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/553.

**Comment by danforbes** [comment]
Reopening this Issue because we should provide this resource as an enhanced README for this repo as opposed to a full-blown tutorial.

**Comment by master-davidlee** [comment]
Ok, that will be fine.

**Comment by wheresaddie** [comment]
going to start working on the documentation, code and reopen this. #sorrynotsorry

**Comment by jimmychu0807** [comment]
@danforbes @wheresaddie 
I am triaging issues in frontend-tpl (finally 😅 ). Do we have an agreement on how to resolve this? 

I don't regard this as an issue of frontend-tpl.

**Comment by wheresaddie** [comment]
@jimmychu0807 I would just update the README to reflect that we likely won't be writing a new tutorial for the front-end template, but we will definitely get some better documentation out there for it and that means archiving or nuking the stuff that doesn't work

**Comment by jimmychu0807** [comment]
@wheresaddie Cool. Thanks.

@master-davidlee wonder are you still working with front-end template? If you are looking for a front-end template tutorial, could you outline for me what kind of content you want to see that is not in the current README.md? Thanks.

**Comment by master-davidlee** [comment]
Yeah thanks. I want to the kitty tutorial back and update to lastest substrate version 


| |
李懿
|
|
邮箱：18920396056@163.com
|

签名由 网易邮箱大师 定制

On 09/24/2020 10:49, Jimmy Chu wrote:

@wheresaddie Cool. Thanks.

@master-davidlee wonder are you still working with front-end template? If you are looking for a front-end template tutorial, could you outline for me what kind of content you want to see that is not in the current README.md? Thanks.

**Comment by jimmychu0807** [comment]
I see. You are talking about the kitty tutorial. It is a piece of work in progress. But kitty tutorial is way beyond the scope of front-end template itself. cc @danforbes also

That being said, we have other tutorials that may satisfy you:

1. [Create Your First Substrate Chain](https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/interact) -  this is for the first time to setup and run your node (you need this for the frontend to connect to)
2. [Build a PoE Decentralized Application](https://substrate.dev/docs/en/tutorials/build-a-dapp/) - this contains the foundational knowledge of writing your own Substrate runtime logic and build a frontend component to interact with it.

Seeing some chinese characters in your reply, do you aware we also have a [zhihu zhuanlan 知乎专栏](https://zhuanlan.zhihu.com/substrate) about Substrate as well. These two pieces of article are about Substrate [frontend](https://zhuanlan.zhihu.com/p/110811972) [development](https://zhuanlan.zhihu.com/p/110815076).

If you use wechat, do follow our official account as well 😉

![IMG_2918](https://user-images.githubusercontent.com/898091/94096469-bf660c00-fe56-11ea-8a54-9bbe029a7f9d.JPG)

I am closing this issue for now.
