### ISSUE TITLE
The Frontend doesn't work on Windows 10

### ISSUE THREAD

**Issue by Mereep** [substrate-developer-hub/substrate-front-end-template#109]
Hello,

I just followed the workflow given [here](https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup) and [here](https://substrate.dev/docs/en/knowledgebase/getting-started/windows-user) to install substrate onto my (Windows 10)-Machine.

The Node - after quite some attempts - could compile and run successfully.
So I followed the tutorial further which brought me here in order to install the substrate frontend template.

I could however not make it run, since `yarn run start` will fail with
```
yarn run start
yarn run v1.22.0
$ PORT=8000 react-scripts start
Der Befehl "PORT" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```
(complaining trying to run PORT which is not a command). After a bit googling, I found that it will basically run that line:
`"start": "PORT=8000 react-scripts start"` which according to the [Yarn-Docs](https://classic.yarnpkg.com/en/docs/cli/run) just runs the PORT command (which is not available). 

So I removed that part (in the hopes its meant as some parameter and has a reasonable default value), which actually made the server start.
However, when attempting to access the web ui, it spills me an error:
```
Error: Child compilation failed:
  Module build failed (from ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js):
  Error: [BABEL] C:\Users\xyz\dev\substrate_frontend\node_modules\webpack\buildin\global.js: Cannot find module '@ba  bel/helper-call-delegate'
  Require stack:
  - C:\Users\Richard\dev\substrate_frontend\node_modules\babel-preset-react-app\node_modules\@babel\plugin-transform-par  ameters\lib\params.js
```
which made me finally report here: I guess thats not suppose to happen.

**Comment by Mereep** [comment]
I could resolve the second issue by:

- purging yarn cache
- manually installing **babel/helper-call-delegate** using `npm i @babel/helper-call-delegate`
- using `npm install ` (instead of the documented `yarn install`)

However, I don't know if step 1 was necessary. Someone might go into details. However, the documentation should reflect that. Installling all of that tool chains is already quite a pain.

**Comment by JoshOrndorff** [comment]
So you have the UI running successfully now?

Did you try running `yarn install` and get an error? If so, please share the error. If you never ran that command, then I'm not surprised it didn't work, you have to install the dependencies first.

`PORT=8000 react-scripts start` works fine in bash on linux. Maybe it doesn't work on Windows. What shell are you using? cmd.exe? power shell? gitbash?

**Comment by danforbes** [comment]
Yeah, I think this is Linux-type syntax for passing and environment variable into a command. It makes sense this would break on Windows. We may want to look into using [a library like `dotenv`](https://www.npmjs.com/package/dotenv) to help with this.

**Comment by Mereep** [comment]
> So you have the UI running successfully now?
yes

> Did you try running yarn install and get an error? 
I used it, it installed successfully. Error happens after start. 
However, after using `npm install` instead, I could start it afterwards

`What shell are you using?`
cmd

**Comment by koalyptus** [comment]
@danforbes @Mereep,
adding the PORT variable to the `.env` file at root:
```bash
EXTEND_ESLINT=true
PORT=8000
```
and modifying the `start` command in `package.json` to read:
```
...
  "scripts": {
    "start": "react-scripts start",
...
```
was enough to make it work under windows.
