### ISSUE TITLE
New Production Endpoint Needed

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-front-end-template#113]
The front end template uses `wss://dev-node.substrate.dev:9944` as the production endpoint for its live deployment:

https://substrate.dev/substrate-front-end-template/

@Tbaut was the one who set up this special dev node, but it has not been updated to latest substrate for a while AFAICT.

So we need to update this node or pick a new endpoint like Polkadot/Westend/Kusama

**Comment by Tbaut** [comment]
Last update was v2.0.0-rc2 some weeks ago. But feel free to use something else, I don't use it myself anymore.

**Comment by shawntabrizi** [comment]
@Tbaut would be happy to grab access from you! DM me :)

**Comment by danforbes** [comment]
Thanks for raising this issue, Shawn. I can take care of updating this DevHub resource as part of the DevHub upgrade process, which I am working on documenting. Now that I am learning more about this situation, I am curious if it is worthwhile to maintain a deployed instance of this template, especially if it requires the maintenance of a special instance of a Substrate node. cc @wheresaddie @JoshOrndorff @jimmychu0807 @riusricardo Ricardo, do you know if we have analytics on the use of the deployed instance of this template?

**Comment by shawntabrizi** [comment]
I would rather maintain the node myself then necessarily see you remove this functionality. I find it quite useful that someone trying to play in our ecosystem has a truly zero effort way to interact with a Substrate blockchain.

Also the overhead of maintenance is quite low, just requires a recompile and a reset every once and a while. Imagine providing deployed substrate nodes that users can interact with at zero effort to the end user.

**Comment by danforbes** [comment]
I think the capability you're describing is provided by the Westend network. From my POV, the expectation around all the DevHub templates is that they will be forked by a developer and deployed locally. Given the existence of other resources like the Polkadot JS Apps UI and the Westend network, I just don't know if a deployed instance of the node and front-end templates offers enough unique value to our users.

**Comment by Tbaut** [comment]
For the record, I gave access to Shawn and briefly explained how I used to manage things. I let you take it from there :)

**Comment by shawntabrizi** [comment]
@danforbes have you tried getting westend tokens? its not very friendly imo, and is quite the uphill battle for someone unfamiliar with our platform

**Comment by danforbes** [comment]
That should be addressed as a separate problem; it doesn't really change my perspective on this issue.

**Comment by shawntabrizi** [comment]
Lets try this, since you have just learned of this feature, please give it the opportunity to exist for 4-6 weeks so you can see and use it in action, and then re-evaluate your decision based on knowledge you have of using it.

There is no reason to start killing off things off that you have not yet used or interacted with.
