### ISSUE TITLE
`yarn start` fails when using VS Code editor

### ISSUE THREAD

**Issue by estill01** [substrate-developer-hub/substrate-front-end-template#123]
Peer-dependency `eslint@6` has a bug that causes `react-scripts` to fail when run in the VS Code text editor. See: https://github.com/microsoft/vscode-eslint/issues/750

It would be helpful to (at minimum) add a warning about this in the README; it took me a nice bit of bug hunting to figure this out and definitely made getting started with Substrate more difficult than it should have been.

**Comment by danforbes** [comment]
Did you encounter an error when you tried to run `yarn start` for this project from the VS Code integrated terminal? I use VS Code and frequently launch this front-end template from the VS Code integrated terminal; I have never encountered a problem. Can you provide some more details about your system, the version of VS Code, etc?

**Comment by wheresaddie** [comment]
thanks for bringing this to our attentions, as @danforbes stated, it would be helpful to know the specific steps that lead to the error or to show us the code snippet so we can update our docs to prevent this in the future

**Comment by jimmychu0807** [comment]
Thanks @estill01 for reporting the issue. This looks more like an issue with vscode and eslint integration, and not about  front-end template itself. 

Am closing this issue for now, but voice out if you strongly think otherwise.
