### ISSUE TITLE
Optional parameters in custom RPC calls are required

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-front-end-template#127]
This issue happens when I add a custom RPC call for the `engine_createBlock` command that comes with manual seal consensus. I modify the template by adding this code in `src/common/config.json:

```json
{
  "APP_NAME": "substrate-front-end-tutorial",
  "DEVELOPMENT_KEYRING": true,
  "RPC": {
    "engine": {
      "createBlock": {
        "description": "Create a new block",
        "params": [
          {
            "name": "create_empty",
            "type": "bool"
          },
          {
            "name": "finalize",
            "type": "bool"
          },
          {
            "name": "parent",
            "type": "Option<BlockHash>"
          }
        ],
        "type": "CreatedBlock"
      }
    }
  }
}
```

Notice that the `parent` field is optional. However, in the UI, the field is still required.

![image](https://user-images.githubusercontent.com/2915325/91178268-e93ede00-e6b2-11ea-8db6-03593f1b0d63.png)

**Comment by NukeManDan** [comment]
I am not sure as this predates me - is this now resolved? If not please do reopen!

I suspect that [type extention/creation](https://polkadot.js.org/docs/api/start/types.create) would be the underlying issue if so that could be patched.
