### ISSUE TITLE
Contracts Component

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-front-end-template#13]
* Import ABI
* Interact with contracts
* more?

**Comment by NukeManDan** [comment]
Is this sufficiently covered in the [ink! workshop](https://substrate.dev/substrate-contracts-workshop/#/0/running-a-substrate-node) with the [canvas UI](https://github.com/paritytech/canvas-ui) to not need this in the template? And of course the main Apps UI.

Or should this still be incorporated?

**Comment by shawntabrizi** [comment]
canvas ui seems like a good replacement for this
