### ISSUE TITLE
Error on start: colorette

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-front-end-template#136]
using npm for the install and running of the template, I get:

```
./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/semantic-ui-css/semantic.min.css)
Error: No valid exports main found for '/home/dan/substrate/substrate-front-end-template/node_modules/colorette'
```

This is as of the most recent release pulled via [instructions here](https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup)

```
git clone -b v2.0.0 --depth 1 https://github.com/substrate-developer-hub/substrate-front-end-template
```

**Comment by NukeManDan** [comment]
likely related to an [older version of node/npm](https://stackoverflow.com/questions/62753723/create-react-app-starting-error-error-no-valid-exports-main-found-for-node)

after and update via `nvm` to 14.13.0 and npm to 6.14.8, it's working :) 

It would be good to specify minimum node required in the dev hub docs as well as in the readme here 🙏🏼

**Comment by wheresaddie** [comment]
great suggestion @NukeManDan 

@danforbes let me know if I can do this or if you prefer to drop it in

**Comment by jimmychu0807** [comment]
@NukeManDan what version of node and nvm you were using before?
