### ISSUE TITLE
ReferenceError: e is not defined

### ISSUE THREAD

**Issue by FitzLu** [substrate-developer-hub/substrate-front-end-template#138]
I followed this article https://substrate.dev/docs/zh-CN/tutorials/build-a-dapp/front-end, replace entire code with the recommend. then yarn start the service and got 'ReferenceError: e is not defined' displaying on the website.
<img width="1027" alt="Screen Shot 2020-10-13 at 21 06 47" src="https://user-images.githubusercontent.com/44373302/95864553-1ac15500-0d98-11eb-8ca2-64fafab8eb91.png">

**Comment by FitzLu** [comment]
my nodejs version is v12.16.2

**Comment by jimmychu0807** [comment]
@FitzLu if you update the line to:

```javascript
<Input
  type='file'
  id='file'
  label='Your File'
  onChange={ e => handleFileChosen(e.target.files[0]) }
/>
```

This should fix it. Sorry for the typo in the docs.

**Comment by wheresaddie** [comment]
yessss! great news @FitzLu .. I will close the issue but if you have any further questions feel free to open a new issue or ping the Riot channels https://substrate.dev/community
