### ISSUE TITLE
Polkadot UI takes forever to load

### ISSUE THREAD

**Issue by ManulSinghParihar** [substrate-developer-hub/substrate-front-end-template#139]
After I compile and run the node-template, I use ```yarn start``` to run the front-end template. I then get redirected to https://localhost:8000/front-end-template which takes forever to load. And then an error stating connection timed out pops up. The node-template works fine and produces blocks as visible in the cli, but the front-end doesn't seem to be working.

**Comment by danforbes** [comment]
Can you please check out your browser's developer console and see if there are any errors? If so, can you please share them as well as a screenshot of the error you're currently seeing pop up?

**Comment by ManulSinghParihar** [comment]
![image](https://user-images.githubusercontent.com/56387534/96027141-15860800-0e75-11eb-9a2e-95a9c56a1b2b.png)
The above screenshot is the working node-template.
![Screenshot (25)](https://user-images.githubusercontent.com/56387534/96027480-904f2300-0e75-11eb-9e7d-f377692cdd28.png)
This screenshot is the same, with the difference of url. This screenshot was taken when I tried using the substrate playground

**Comment by danforbes** [comment]
If you get that screen when you try to access the front-end template it means that the front-end template is not running locally on your machine. Can you please ensure that you have started the front-end template with `yarn start`? If you do and you still get errors, please share those errors including whatever you see in the developer console.

**Comment by ManulSinghParihar** [comment]
Yup, I can assure you that I did use ```yarn start``` to start the front-end template. I will share the screenshot with you in a while.

**Comment by jimmychu0807** [comment]
Just want to double check, you do run `yarn install` before you run `yarn start`, right?

**Comment by wheresaddie** [comment]
`yarn install` needs to be done globally before you attempt to run or start 'yarn' within the front-end template etc. This can also cause issues

**Comment by ManulSinghParihar** [comment]
Now that you all have mentioned ```yarn install```, I am quite skeptical, if I did that or not. I will give it a try and let you all know. Thanks for the suggestion.

**Comment by NukeManDan** [comment]
I can confirm, any edits take ~ 30 seconds to register for my FE template. This makes dev time to check on progress slow...

**Comment by ManulSinghParihar** [comment]
Thanks for your help everyone. The front-end is now working.

**Comment by danforbes** [comment]
@NukeManDan I checked on my side and confirmed that the live reloading capabilities of the front-end template are working as I'd expect them to on my machine.

**Comment by NukeManDan** [comment]
I didn't realize at the time, I was running a polkadot node at the time, and I suspect this was the issue. It might be the larger api metadata for the node returned exposing more for the FE to ingest and render...?

More likely it is related to the `sudo` account not being available, leading to errors (I think reported on the matrix/discord chat).

It _might_ be a worthwhile exercise to benchmark startup/re-render times on a polkadot node @danforbes, but likely not going to be an issue for most. Mostly to see if missing sudo or other pallets make the UI take a while to load.
