### ISSUE TITLE
Add module checks for all components

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-front-end-template#14]
Check the module being used by a component actually exists before rendering a component or making calls, else it will crash the site.

**Comment by JoshOrndorff** [comment]
Examples of how to do such a check https://github.com/substrate-developer-hub/substrate-ui-template/blob/8d01a81cf5c3f83def720259afd5468d0c35138e/src/App.jsx#L137-L141

**Comment by shawntabrizi** [comment]
An updated way to do this check is here:
https://github.com/substrate-developer-hub/substrate-front-end-template/commit/37a0622411b41f90bcda6ab885f829ec43205818

It keeps the check within the component itself, which is a pattern we should TOTALLY be following here.

**Comment by JoshOrndorff** [comment]
Agree, this is a good idea. What's the motivation for returning `null`? It otherwise would have returned `false` I think.

**Comment by shawntabrizi** [comment]
An empty render should return `null`:
https://stackoverflow.com/questions/42083181/is-it-possible-to-return-empty-in-react-render-function

Returning anything like `false` wont work as it expects some component.
