### ISSUE TITLE
Template deps does not cater for Substrate 2.0

### ISSUE THREAD

**Issue by jacogr** [substrate-developer-hub/substrate-front-end-template#141]
You need > 2.0 to ensure you have all the latest types, including RefCount which was introduced in Substrate 2.0 (final)

Would appreciate an update since the mismatch is causing support overhead my side - https://github.com/polkadot-js/api/issues/2733#issuecomment-709415560 (Love helping with support, but in this case, it is a clear mistake)

**Comment by jacogr** [comment]
Ok there is a PR for this, get it in - https://github.com/substrate-developer-hub/substrate-front-end-template/pull/140

**Comment by jimmychu0807** [comment]
yea, am aware of that. Thanks for the note @jacogr !
