### ISSUE TITLE
The url of Front-end-tutorial has gone

### ISSUE THREAD

**Issue by master-davidlee** [substrate-developer-hub/substrate-front-end-template#147]
The url of Front-end-tutorial has gone

**Comment by wheresaddie** [comment]
are you referring to this one? https://substrate.dev/docs/ru/tutorials/build-a-dapp/front-end

please share the link, thanks!

**Comment by master-davidlee** [comment]
NO This repo's README file 
![2020-10-19 14-26-04 的屏幕截图](https://user-images.githubusercontent.com/49427668/96408935-132a0200-1217-11eb-9c77-53fe9afc5baf.png)

**Comment by wheresaddie** [comment]
please feel free to update and post PR to push, 

https://substrate.dev/en/tutorials

thanks!
