### ISSUE TITLE
Display the connected node address

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-front-end-template#152]
Likely at the top of the dashboard

**Comment by riusricardo** [comment]
Or something like the metadata, in a popup windows.

**Comment by NukeManDan** [comment]
https://substrate.dev/substrate-front-end-template/ this does have a button in the metadata card (top, send from the left) - specifically the JSON formatted _runtime_ metadata

So a new button to show more node specific metadata?

**Comment by riusricardo** [comment]
I'm not sure what Jimmy wants but it could be good to display the nodes connected to your node.
