### ISSUE TITLE
Add a detailed title introduction to the front page.

### ISSUE THREAD

**Issue by 99Kies** [substrate-developer-hub/substrate-front-end-template#153]
![image](https://user-images.githubusercontent.com/45918704/101939638-3b831b00-3c20-11eb-945b-ff6b5234b4b0.png)

**Comment by danforbes** [comment]
I think this is a great suggestion, @99Kies! Would you care to make a PR?

**Comment by 99Kies** [comment]
> I think this is a great suggestion, @99Kies! Would you care to make a PR?

i need help. I don't know the canonical names for these three types of data.
![image](https://user-images.githubusercontent.com/45918704/102710803-dac6a300-42ef-11eb-9d18-2becf16a4c91.png)

**Comment by 99Kies** [comment]
#155

**Comment by danforbes** [comment]
Sorry for the delay, @99Kies and thank you for the contribution! Please reopen this Issue if you think it's not completely resolved but I'm going to close it for now.
