### ISSUE TITLE
[u8;32] type not accepted in transactions

### ISSUE THREAD

**Issue by spencerbh** [substrate-developer-hub/substrate-front-end-template#157]
I have this extrinsic:
[createApnAccount](https://github.com/spencerbh/BLX_chain_future/blob/f94a93dfdb25a2adc31c903cb3039a547763c0c6/pallets/claimer/src/lib.rs#L524)

I have set up a frontend template with src/config/types.json :
```  
/* -- snip -- */   
"APN": "[u8;32]",  
/* -- snip -- */ 
```
I get an error:
> REGISTRY: Error: Call: failed decoding claimer.createApnAccount:: Struct: failed on args: {"proxy_type":"ProxyType","delay":"BlockNumber","index":"u16","APN":"[u8;32]"}:: Struct: failed on APN: [u8;32]:: value.subarray is not a function

If I use the Polkadot js appsUI i am able to execute the txn without error. I am fairly certain the front end template is failing due to the need for me to modify some step in the decoding, but since I am able to execute the txn on AppsUI I am opening this issue :)

**Comment by NukeManDan** [comment]
Sorry for the very late reply here - if this is still an issue after reviewing [the api docs](https://polkadot.js.org/docs/api/start/types.create) on this, please reopen and/or come get support on [the substrate matrix chat](https://matrix.to/#/#substrate-technical:matrix.org)

**Comment by spencerbh** [comment]
continued here: https://stackoverflow.com/questions/66838308/front-end-template-types-decoding-issue-value-subarray-is-not-a-function
