### ISSUE TITLE
Error: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime

### ISSUE THREAD

**Issue by tansaku** [substrate-developer-hub/substrate-front-end-template#158]
I'm just following the tutorial at https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/interact on OSX 11.1 and rust 14.9. - I needed to bump the backend to version 2.0.1 to get the back end to work.

The front end runs and trying to do any transfer I get the error in the subject line:

```
😞 Transaction Failed: Error: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress: RuntimeApi, Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress
```

<img width="1530" alt="Screenshot 2021-01-19 at 16 50 27" src="https://user-images.githubusercontent.com/30216/105066066-7d507e00-5a76-11eb-96e8-2d68fe884055.png">

I see this being chatted about in the element chat room but could not see anyone mentioning a fix - any suggestions?

**Comment by danforbes** [comment]
You should be using the v2.0.0 tag of the Front-End Template with the v2.0.0 tag of the Node Template. This should alleviate the problem - if so, please close this Issue.

**Comment by tansaku** [comment]
Unfortunately the v2.0.0 tag of the node template doesn't work (https://stackoverflow.com/questions/65600537/error-while-build-errore0282-type-annotations-needed/65756888#65756888) - upgrading the node template to v2.0.1 was the only fix that allows me to run the backend, so I'm blocked either way.

Is there not a v2.0.1 of the front end?

I've put in a PR to upgrade the documentation to specify v2.0.1 on the back end https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/830 but sounds like that's not appropriate if it's not compatible with the v2.0.0 front end ...

**Comment by mcbucks** [comment]
> Unfortunately the v2.0.0 tag of the node template doesn't work for me (https://stackoverflow.com/questions/65600537/error-while-build-errore0282-type-annotations-needed/65756888#65756888) - upgrading the node template to v2.0.1 was the only fix that allows me to run the backend, so I'm blocked either way.
> 
> Is there not a v2.0.1 of the front end?
> 
> I've put in a PR to upgrade the documentation to specify v2.0.1 on the back end [substrate-developer-hub/substrate-developer-hub.github.io#830](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/830) but sounds like that's not appropriate if it's not compatible with the v2.0.0 front end ...

got the same problem

**Comment by westdabestdb** [comment]
Same issue here

**Comment by NukeManDan** [comment]
Here is a fix for those struggling with the frontend v2.0.0 using the node (backend) v2.0.1:

Edit the following file to set the `AccountId` fields to `Multiaddress`
### src/config/types.json
```
{
"Address": "MultiAddress",
"LookupSource": "MultiAddress"
}
```

**Comment by mcbucks** [comment]
> If you are using the node (backend) v2.0.1: Here is a fix for those struggling with the frontend v2.0.0. instead you should use the `master` branch of the frontend repo
> 
> To get the master branch cloned:
> 
> ```shell
> git clone -b master --depth 1 https://github.com/substrate-developer-hub/substrate-front-end-template
> ```
> 
> and then edit the following file for the frontend to replace the `AccountId` fields to `MultiAddress`
> 
> ### src/config/types.json
> ```
> {
> "Address": "MultiAddress",
> "LookupSource": "MultiAddress"
> }
> ```
> 
> Then install packages and start the dev server:
> 
> ```
> cd substrate-front-end-template
> yarn install
> yarn start
> ```
> 
> I have made a patch to use instead of manually editing the file you could use instead as well:
> 
> ```
> git clone -b NukeManDan-patch-1 --depth 1 https://github.com/substrate-developer-hub/substrate-front-end-template
> ```
> 
> #159 should fix the issue.

works for me

**Comment by tansaku** [comment]
I cloned the patched version but it didn't work for me - when I inspected the `src/config/types.json` file it contained only `{}` and then I added the specified:

```
{
    "Address": "MultiAddress",
    "LookupSource": "MultiAddress"
}
```

everything worked, so maybe the patch is missing a commit or something?

**Comment by westdabestdb** [comment]
Works for me, thank you.

**Comment by tansaku** [comment]
although I note that the balances are not updating in the fashion advertised ...

![Screenshot 2021-01-22 at 15 38 19](https://user-images.githubusercontent.com/30216/105511626-01e60b00-5cc8-11eb-8948-2d92bc0da335.png)
<img width="692" alt="Screenshot 2021-01-22 at 15 35 54" src="https://user-images.githubusercontent.com/30216/105511627-027ea180-5cc8-11eb-8a21-49f1f8ea258f.png">

**Comment by NukeManDan** [comment]
@tansaku #159 I report that I see it working on a restart of the dev server with or without the types added - can you try this the empty {} ?

Also it appears you are transferring to Alice, what account are you using to send from? (not pictured) I suspect you are sending Alice->Alice.

**Comment by tansaku** [comment]
thanks @NukeManDan you're correct I was logged in as Alice, but my transfers to Bob were also not working, but I have figured it out - the 1000000000000 unit transfers were not showing up for Bob as he already head MUnit amounts.  I transferred to Charlie and that worked, and when I transferred 1000000000000000000 to Bob that showed up.

Restarting with the empty {} gives the same error as before:

> 😞 Transaction Failed: Error: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress: RuntimeApi, Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress

but adding in the MultiAddress settings makes it all work fine.  I tried the empty {} with restarts of both front and back end to no avail, but with the MultiAddress change I'm good to go - thanks so much for your help.

**Comment by tansaku** [comment]
hi folks - has anyone tried the smart ink tutorials?  I've getting the same error that we saw here, but now with the paritytech.github.io/canvas-ui front end:

https://github.com/substrate-developer-hub/substrate-contracts-workshop/issues/100
