### ISSUE TITLE
UI should show connection errors to the user

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-front-end-template#16]
When failing to specify correct types (and probably other things) polkadot api puts a helpful error in the console. However this never makes it to the UI.

Just how technical of messages should be passed onto the UI is open for debate, but at least the user should know that connecting has failed and they shouldn't just sit there waiting.

**Comment by JoshOrndorff** [comment]
![image](https://user-images.githubusercontent.com/2915325/64193393-a6a14780-ce4a-11e9-9be5-e23dd822560f.png)

**Comment by jimmychu0807** [comment]
Duplicate #73
