### ISSUE TITLE
Unhandled Rejection (Error)

### ISSUE THREAD

**Issue by magj2006** [substrate-developer-hub/substrate-front-end-template#160]
if I input alics as account to query balance, then Unhandled Rejection (Error): happened as below snapshot shown.

<img width="622" alt="屏幕快照 2021-01-24 下午7 00 49" src="https://user-images.githubusercontent.com/8394789/105634163-8ed2c500-5e7e-11eb-832c-4ef4f88a0377.png">

<img width="1048" alt="屏幕快照 2021-01-24 下午6 59 41" src="https://user-images.githubusercontent.com/8394789/105634168-97c39680-5e7e-11eb-8d0d-47c7225c4210.png">

I am using v2.0.1 of substrate node template and v2.0.0 of substrate front end template.

**Comment by jimmychu0807** [comment]
@magj2006 you need to fill in with the full Alice address, which you can copy from the above Balance widget (by clicking the small clipboard logo). It should be `5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY`. 

Let me know if it doesn't work. I am closing this now.

**Comment by magj2006** [comment]
@jimmychu0807 you are right.  Actually I want to test what happened if input something which is not real account id, I think it's not good for user to show this.
