### ISSUE TITLE
Build a PoE Decentralized Application example TypeError: api.tx[palletRpc][callable] is not a function

### ISSUE THREAD

**Issue by jsoneaday** [substrate-developer-hub/substrate-front-end-template#161]
**Description**
Hello I'm trying to get the above sample app working, while using the Substrate-Front-End-Template, and encountering the error given after clicking the Create Claim button in the Proof of Existence section of the screen. The error occurs in the src/substrate-lib/components/TxButton.js file, in the function signedTx. 

Basically the call to api.tx[palletRpc][callable] is not found (in the debugger the variable palletRpc = "templateModule" and callable = "createClaim"). To be specific the member templateModule is found but not its member createClaim. The only members I can see in the templateModule inside of the debugger are causeError and doSomething.

Is there a JavaScript api reference somewhere like the one for Rust?

**Steps to Reproduce**
1. Start React app, Substrate-Front-End-Template, after starting local dev instance of Substrate-Node-Template
2. Use Proof of Existence section to pick a file and then click the Create Claim button

**Environment**
- Operating system: macOS
- Template version/tag: 2.0.1 for node template, 0.1.1 for front end template
- Rust version (run rustup show): 1.49.0

**Logs, Errors, or Screenshots**
I've placed a break point right before the error above happens.
![image](https://user-images.githubusercontent.com/1474935/106041481-da1ceb80-60a9-11eb-9d55-68a2a143f4f3.png)

**Comment by al3mart** [comment]
Sounds like you have not implemented the logic around creating and revoking claims. I will make sure that you have covered this part of the tutorial too :)
https://substrate.dev/docs/en/tutorials/build-a-dapp/pallet#callable-functions

**Comment by jsoneaday** [comment]
Thank you very much for your help, but no that wasn't it. I had already filled that piece out and I even tried deleting my code and copy and pasting the stuff from the page you gave me (just in case i missed something). I still get the same error as before. Which again is happening on the front end side (React app), not on the node template. For some reason the api.tx.templateModule object is missing some expected members.

![image](https://user-images.githubusercontent.com/1474935/106299607-5c7ceb00-6223-11eb-9759-013a35b00d19.png)

**Comment by al3mart** [comment]
mmmh, I would like @jimmychu0807 having a look at this, maybe he can bring some insight :) I'll keep on checking meanwhile

**Comment by jsoneaday** [comment]
I suspect it’s probably something to do with the versions I’m on. 2.0.0 was giving me errors so I had upgraded to 2.0.1

Sent from my iPhone

On Jan 29, 2021, at 3:16 PM, Alejandro Martinez Andres <notifications@github.com> wrote:

﻿

mmmh, I would like @jimmychu0807<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjimmychu0807&data=04%7C01%7C%7C40bb0078c7c44bb717f708d8c492cd11%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637475482072769775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K7VTv8Nz9LPbBaH6pYijmzs1%2FCHcNvfoVzqa8DY9u64%3D&reserved=0> having a look at this, maybe he can bring some insight :) I'll keep on checking meanwhile

**Comment by jsoneaday** [comment]
I suspect it’s probably something to do with the versions I’m on. 2.0.0 was giving me errors so I had upgraded to 2.0.1

Here's a screenshot of the console.log of the api.tx.templateModule object.

![image](https://user-images.githubusercontent.com/1474935/106329055-cf4f8b80-624e-11eb-96b1-8139d54163c3.png)

**Comment by jimmychu0807** [comment]
@jsoneaday so do you encounter any error when using Substrate v2.0.1?

**Comment by jsoneaday** [comment]
This issue is occurring on 2.0.1. I was having a compilation issue on 2.0.0 and that's why I moved to 2.0.1.

**Comment by magj2006** [comment]
@jsoneaday I completed successfully PoE using 2.0.1, so I think you maybe missing some logic. 
<img width="570" alt="屏幕快照 2021-02-01 下午10 38 37" src="https://user-images.githubusercontent.com/8394789/106496053-4058a280-64de-11eb-8031-cafac1e529d5.png">
<img width="1166" alt="屏幕快照 2021-02-01 下午10 39 23" src="https://user-images.githubusercontent.com/8394789/106496186-6a11c980-64de-11eb-92ba-5df3016c4de8.png">

**Comment by jsoneaday** [comment]
Ok thanks I'll try again from the start of the sample.
________________________________

**Comment by jsoneaday** [comment]
So I went back and re-copied and pasted all of the code, both node-template and front-end-template. The issue that I'm having now is that on the updated TemplateModule.js file in the last function TemplateModule the check for api.query.templateModule.proofs is coming back as undefined. This causes the loading of TemplateModule.js' Main function to not happen and therefore I don't get the UI for the Proof Of Existence section.

![image](https://user-images.githubusercontent.com/1474935/106509601-d0c1c380-649b-11eb-9f72-420088d40578.png)

**Comment by jimmychu0807** [comment]
@jsoneaday I can only help you if I can see the Substrate side of the code. Because everything after `api.query.*` is generated dynamically according to the [Substrate metadata](https://substrate.dev/docs/en/knowledgebase/runtime/metadata). So it is different for every Substrate chain based on how Substrate runtime is implemented (and thus your Substrate code).

If `.proofs` is coming back as undefined, that means in your `templateModule`, you do not define the `Proofs` storage. Do you have [this piece of code](https://substrate.dev/docs/en/tutorials/build-a-dapp/pallet#storage) in your template module, and have the executable compiled?

**Comment by jsoneaday** [comment]
Yes I have that code. As I mentioned earlier I decided to remove my code and copy and paste directly from the sample code, in case I had missed something. I am simply following the Build a PoE Decentralized Application. Here is my entire pallets/template/src/lib.rs file.

`#![cfg_attr(not(feature = "std"), no_std)]

use frame_support::{
    decl_module, decl_storage, decl_event, decl_error, ensure, StorageMap
};
use frame_system::ensure_signed;
use sp_std::vec::Vec;

/// Configure the pallet by specifying the parameters and types on which it depends.
pub trait Trait: frame_system::Trait {
    /// Because this pallet emits events, it depends on the runtime's definition of an event.
    type Event: From<Event<Self>> + Into<<Self as frame_system::Trait>::Event>;
}

// Pallets use events to inform users when important changes are made.
// Event documentation should end with an array that provides descriptive names for parameters.
// https://substrate.dev/docs/en/knowledgebase/runtime/events
decl_event! {
    pub enum Event<T> where AccountId = <T as frame_system::Trait>::AccountId {
        /// Event emitted when a proof has been claimed. [who, claim]
        ClaimCreated(AccountId, Vec<u8>),
        /// Event emitted when a claim is revoked by the owner. [who, claim]
        ClaimRevoked(AccountId, Vec<u8>),
    }
}

// Errors inform users that something went wrong.
decl_error! {
    pub enum Error for Module<T: Trait> {
        /// The proof has already been claimed.
        ProofAlreadyClaimed,
        /// The proof does not exist, so it cannot be revoked.
        NoSuchProof,
        /// The proof is claimed by another account, so caller can't revoke it.
        NotProofOwner,
    }
}

// The pallet's runtime storage items.
// https://substrate.dev/docs/en/knowledgebase/runtime/storage
decl_storage! {
    trait Store for Module<T: Trait> as TemplateModule {
        /// The storage item for our proofs.
        /// It maps a proof to the user who made the claim and when they made it.
        Proofs: map hasher(blake2_128_concat) Vec<u8> => (T::AccountId, T::BlockNumber);
    }
}

// Dispatchable functions allows users to interact with the pallet and invoke state changes.
// These functions materialize as "extrinsics", which are often compared to transactions.
// Dispatchable functions must be annotated with a weight and must return a DispatchResult.
decl_module! {
    pub struct Module<T: Trait> for enum Call where origin: T::Origin {
        // Errors must be initialized if they are used by the pallet.
        type Error = Error<T>;

        // Events must be initialized if they are used by the pallet.
        fn deposit_event() = default;

        /// Allow a user to claim ownership of an unclaimed proof.
        #[weight = 10_000]
        fn create_claim(origin, proof: Vec<u8>) {
            // Check that the extrinsic was signed and get the signer.
            // This function will return an error if the extrinsic is not signed.
            // https://substrate.dev/docs/en/knowledgebase/runtime/origin
            let sender = ensure_signed(origin)?;

            // Verify that the specified proof has not already been claimed.
            ensure!(!Proofs::<T>::contains_key(&proof), Error::<T>::ProofAlreadyClaimed);

            // Get the block number from the FRAME System module.
            let current_block = <frame_system::Module<T>>::block_number();

            // Store the proof with the sender and block number.
            Proofs::<T>::insert(&proof, (&sender, current_block));

            // Emit an event that the claim was created.
            Self::deposit_event(RawEvent::ClaimCreated(sender, proof));
        }

        /// Allow the owner to revoke their claim.
        #[weight = 10_000]
        fn revoke_claim(origin, proof: Vec<u8>) {
            // Check that the extrinsic was signed and get the signer.
            // This function will return an error if the extrinsic is not signed.
            // https://substrate.dev/docs/en/knowledgebase/runtime/origin
            let sender = ensure_signed(origin)?;

            // Verify that the specified proof has been claimed.
            ensure!(Proofs::<T>::contains_key(&proof), Error::<T>::NoSuchProof);

            // Get owner of the claim.
            let (owner, _) = Proofs::<T>::get(&proof);

            // Verify that sender of the current call is the claim owner.
            ensure!(sender == owner, Error::<T>::NotProofOwner);

            // Remove claim from storage.
            Proofs::<T>::remove(&proof);

            // Emit an event that the claim was erased.
            Self::deposit_event(RawEvent::ClaimRevoked(sender, proof));
        }
    }
}`

**Comment by riusricardo** [comment]
@NukeManDan @jimmychu0807 Is this issue still relevant or has been fixed after the tutorial update?

**Comment by NukeManDan** [comment]
When https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/883 is closed, this one should be deprecated and can be closed. We can close this now, as we expect that one to land soon, Sacha is on it I see.
