### ISSUE TITLE
Transfer: Transaction Failed: Error: 1002: Verification Error: Execution #136

### ISSUE THREAD

**Issue by rossbulat** [substrate-developer-hub/substrate-front-end-template#162]
**Description**

I have followed the first Substrate tutorial and have attempted to make a transfer like the tutorial suggests. The transfer function fails:

```
😞 Transaction Failed: Error: 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress: RuntimeApi, Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress
```

**Steps to Reproduce**

Attempt to make a transfer.

**Environment**

- Operating system: macOS 11.1
- Template version/tag: 2.0.0
- Rust version (run `rustup show`): 1.49.0

**Logs, Errors or Screenshots**
![sn_error](https://user-images.githubusercontent.com/13929023/106086859-d5dce680-611a-11eb-98ae-6f1b38ba460d.jpg)

**Comment by jimmychu0807** [comment]
@rossbulat  @krisquigley 
Yes, the substrate-node-template v2.0.1 has a change on how it is treating `Address` and `LookupSource`. Refer to [code here](https://github.com/substrate-developer-hub/substrate-front-end-template/blob/master/src/config/types.json). So it is expected to work with [substrate-node-template v2.0.1](https://github.com/substrate-developer-hub/substrate-node-template/tree/v2.0.1), and **NOT** v2.0.0. 

Let me know if you run into the same problem if connecting to Substrate/node template v2.0.1. Thanks.

**Comment by rossbulat** [comment]
That is fair, not sure 2.0.1 was released when I originally tested. Will give it a shot, thanks

**Comment by NukeManDan** [comment]
V3 is out now and should solve any issue like this - you of course will need to use the correct major version number (v2 or v3) for all templates to expect them to work.
