### ISSUE TITLE
React-app Substrate

### ISSUE THREAD

**Issue by J-Cook-jr** [substrate-developer-hub/substrate-front-end-template#167]
When cloning this repo, are we supposed to "Create React App" first and then clone the repo into the react project? I'm asking because I got this message in my terminal after running yarn install...
<img width="1280" alt="Screen Shot 2021-03-15 at 1 55 41 PM" src="https://user-images.githubusercontent.com/62865359/111198790-5a35dc80-8596-11eb-9816-a717757b8fb2.png">

**Comment by jimmychu0807** [comment]
No, running with this repo should be enough. From the last line, it is saying able to complete downloading all dependencies, just with warnins.

Are you able to start the frontend template with `yarn start`?

**Comment by NukeManDan** [comment]
@J-Cook-jr let's handle this over in https://github.com/paritytech/subport , or better yet, on the matrix chat if you are still having issues 🙏🏼
