### ISSUE TITLE
Error Connecting to substrate

### ISSUE THREAD

**Issue by J-Cook-jr** [substrate-developer-hub/substrate-front-end-template#169]
Hi, I'm getting this error after building and starting the front-end template:

<img width="1196" alt="Screen Shot 2021-03-30 at 2 08 12 PM" src="https://user-images.githubusercontent.com/62865359/113047012-c3a91400-916e-11eb-9afc-852ea66000b4.png">

As you can see, I have my v3.0.0 node running :
<img width="1280" alt="Screen Shot 2021-03-30 at 3 41 39 PM" src="https://user-images.githubusercontent.com/62865359/113047089-dc192e80-916e-11eb-88c2-79371216a027.png">

Please help, Thanks!

**Comment by J-Cook-jr** [comment]
I believe 3.0.0 . Where in the cloned repo can I verify this?

**Comment by NukeManDan** [comment]
`git log` will show the commit and messages

**Comment by J-Cook-jr** [comment]
I'm using the Master version

**Comment by NukeManDan** [comment]
use v3

**Comment by J-Cook-jr** [comment]
Will do. Thank you sir! 👍

**Comment by J-Cook-jr** [comment]
When cloning the repo for substrate front end template v3.0.0, I don't see a difference between the Master clone command. Is there a specific command to tell the terminal to download v3.0.0 or will it automatically do this as long as I copy the command from the v3.0.0 tagged repo?

**Comment by NukeManDan** [comment]
if you clone the repo you can checkout any branch. 

`git checkout v3.0.0`

**Comment by NukeManDan** [comment]
try clearing you cache and cookies for the site too and then connect when your node is already running

Also try to connect with https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/

**Comment by J-Cook-jr** [comment]
Ok , I'll try those steps. polkadot.j.org didn't have any connection issues, I just didn't quite understand what I was doing with the interface. I have had a little more experience with substrate-front-end template, therefore I'm more comfortable with using it. I am now beginning to learn my way around polkadot.js.org.

**Comment by J-Cook-jr** [comment]
After I cloned the repo , I ran yarn install. Do I need to run the command again after I switch to the v3.0.0 branch?

**Comment by J-Cook-jr** [comment]
I'm still getting the same error after switching to v3.0.0 and I've cleared my browser cache.

**Comment by NukeManDan** [comment]
not sure at this point, as the main UI seems to function as expected. I can't reproduce locally either. It works just fine for me. 🤷🏼 

Try using the main UI to learn it in the mean time? 

What does your browser console log report? any errors?
`ctrl+shift+i`
![image](https://user-images.githubusercontent.com/35669742/113057370-2fd54900-916a-11eb-90ed-0ab02d0c0bbb.png)

**Comment by J-Cook-jr** [comment]
I'll check as soon as I finish recompiling my substrate node template.

**Comment by J-Cook-jr** [comment]
I've deleted the tests from my kitties_pallet to move things along until you got back with me. Everything compiled successfully but could that be a reason for this connection error?

**Comment by J-Cook-jr** [comment]
Also, what do you mean when you say "Main UI"? Is that a different front-end-template?

**Comment by NukeManDan** [comment]
> What does your browser console log report for the FE template page? any errors?
> `ctrl+shift+i`
