### ISSUE TITLE
Substrate Front End Template not worked

### ISSUE THREAD

**Issue by PankajChaudhary5** [substrate-developer-hub/substrate-front-end-template#174]
After run the command 
**yarn install** in the template. It is giving the error.

**Error:**
/home/knoldus/Desktop/substrate-front-end-template/.yarn/releases/yarn-berry.cjs:2
module.exports=(()=>{var e={25545:e=>{function t(e){var t=new Error("Cannot find module '"+e+"'");throw t.code="MODULE_NOT_FOUND",t}t.keys=()=>[],t.resolve=t,t.id=25545,e.exports=t},44692:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>g});var A=r(54143);const n={optional:!0},o=[["@samverschueren/stream-to-observable@<0.3.1",{peerDependenciesMeta:{rxjs:n,zenObservable:n}}],["any-observable@<0.5.1",{peerDependenciesMeta:{rxjs:n,zenObservable:n}}],["@pm2/agent@<1.0.4",{dependencies:{debug:"*"}}],["debug@<4.2.0",{peerDependenciesMeta:{"supports-color":n}}],["got@<11",{dependencies:{"@types/responselike":"^1.0.0","@types/keyv":"^3.1.1"}}],["cacheable-lookup@<4.1.2",{dependencies:{"@types/keyv":"^3.1.1"}}],["http-link-dataloader@*",{peerDependencies:{graphql:"^0.13.1 || ^14.0.0"}}],["typescript-language-server@*",{dependencies:{"vscode-jsonrpc":"^5.0.1","vscode-languageserver-protocol":"^3.15.0"}}],["postcss-syntax@*",{peerDepend

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by NukeManDan** [comment]
- How did you install your node template?
- What commit specifically are you trying to build of this repo?
- What are your machine specifications?
  - `yarn` version
  - OS
  - `node` version

**Comment by PankajChaudhary5** [comment]
I just cloned it and following the document https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/
Commit Info: 
commit 5c6d8293e4afc1c0736865da5c5f0010d6d72950 (HEAD -> master, origin/master, origin/HEAD)
Author: Dan Shields <35669742+NukeManDan@users.noreply.github.com>
Date:   Sat May 1 02:25:33 2021 -0600

    Display the connected node addr & fork me banner (#172) (#173)
    
    Co-authored-by: Jimmy Chu <jimmy@parity.io>

Machine Specifications:
yarn version: 1.22.10
OS: Linux(Ubuntu 18.04)
node version: 1.22.10
