### ISSUE TITLE
ERROR RUNNING YARN INSTALL

### ISSUE THREAD

**Issue by kcelestinomaria** [substrate-developer-hub/substrate-front-end-template#176]
I am running on Ubuntu 20.04  OS version, in a VM, cloned the substrate front end template and then ran yarn install to set up dependencies and there is a certain git repo that acts as a dependency to the template but has either been deleted or privatized, at least that is what the error is saying here, please read: `Error: bip32-ed25519@git+ssh://git@github.com/Zondax/bip32-ed25519.git#commit=0949df01b5c93885339bc28116690292088f6134: Repository clone failed: Child "git" exited with exit code 128

Cloning into '/tmp/xfs-c34c969e'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (/root/Substrate-node-template-Harambee/substrate-front-end-template/.yarn/releases/yarn-berry.cjs:2:404557)
    at ChildProcess.emit (node:events:365:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:365:28)
    at Pipe.<anonymous> (node:net:661:12) {
  code: 128,
  stdout: '',
  stderr: "Cloning into '/tmp/xfs-c34c969e'...\n" +
    'Host key verification failed.\r\n' +
    'fatal: Could not read from remote repository.\n' +
    '\n' +
    'Please make sure you have the correct access rights\n' +
    'and the repository exists.\n'
}`

**Comment by NukeManDan** [comment]
https://github.com/Zondax/bip32-ed25519
looks public to me.

Are you using yarn v2? what version are you using? Try v1 and v2

**Comment by kcelestinomaria** [comment]
Hello @NukeManDan , was using yarn v1 but when I shifted to yarn v2 the problem persisted, same problem

**Comment by kcelestinomaria** [comment]
Could it be that some configurations where changed on that repo? Maybe even the ssh key, check the error: `Error: bip32-ed25519@git+ssh://git@github.com/Zondax/bip32-ed25519.git#commit=0949df01b5c93885339bc28116690292088f6134: Repository clone failed: Child "git" exited with exit code 128

Cloning into '/tmp/xfs-d7ed8a76'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (/root/Substrate-node-template-Harambee/substrate-front-end-template/.yarn/releases/yarn-2.4.1.cjs:2:405637)
    at ChildProcess.emit (node:events:365:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:365:28)
    at Pipe.<anonymous> (node:net:661:12) {
  code: 128,
  stdout: '',
  stderr: "Cloning into '/tmp/xfs-d7ed8a76'...\n" +
    'Host key verification failed.\r\n' +
    'fatal: Could not read from remote repository.\n' +
    '\n' +
    'Please make sure you have the correct access rights\n' +
    'and the repository exists.\n'
}`

**Comment by kcelestinomaria** [comment]
It seems like a problem with the host key verification from that repo as it explicitly suggests

`` stderr: "Cloning into '/tmp/xfs-d7ed8a76'...\n" +
    'Host key verification failed.\r\n' +
    'fatal: Could not read from remote repository.\n' +
    '\n' +
    'Please make sure you have the correct access rights\n' +
    'and the repository exists.\n'
}``

**Comment by NukeManDan** [comment]
Do you have your github ssh keys setup on the VM correctly?

**Comment by kcelestinomaria** [comment]
Hello @NukeManDan , I didn't have my github ssh keys on my VM, so I initated new ones and connected to my account, then tested it, but still the problem persists

**Comment by kcelestinomaria** [comment]
Same error:  

```Error: bip32-ed25519@git+ssh://git@github.com/Zondax/bip32-ed25519.git#commit=0949df01b5c93885339bc28116690292088f6134: Repository clone failed: Child "git" exited with exit code 128

Cloning into '/tmp/xfs-198de191'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (/root/Substrate-node-template-Harambee/substrate-front-end-template/.yarn/releases/yarn-2.4.1.cjs:2:405637)
    at ChildProcess.emit (node:events:365:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:365:28)
    at Pipe.<anonymous> (node:net:661:12) {
  code: 128,
  stdout: '',
  stderr: "Cloning into '/tmp/xfs-198de191'...\n" +
    'git@github.com: Permission denied (publickey).\r\n' +
    'fatal: Could not read from remote repository.\n' +
    '\n' +
    'Please make sure you have the correct access rights\n' +
    'and the repository exists.\n'
}```

**Comment by kcelestinomaria** [comment]
To add, here is the yarn version as well that I am using:  ```root@localhost:~/Substrate-node-template-Harambee/substrate-front-end-template# yarn --version
2.4.1```

**Comment by kcelestinomaria** [comment]
I am guessing there have been breaking changes recently and that repo became incompatible with the changes

**Comment by kcelestinomaria** [comment]
Hello, problem solved when using ```npm install && npm start``` . However, curious why yarn does not work in this case, I think it is something worthwhile to follow up.

**Comment by NukeManDan** [comment]
Your version of Yarn is likely the issue. v1 is used IIRC. v2 may not work (or vice-versa) I will open an issue to update to v2. What were you using?

**Comment by brenzi** [comment]
I'm facing the same issue. Our gh-pages action worked a month ago, but now fails with exactly the above error

I tried locally with

**Comment by brenzi** [comment]
was able to fix it by manually editing yarn.lock and replacing the git+ssh by git+https: url
