### ISSUE TITLE
Unable to see any balance 

### ISSUE THREAD

**Issue by discovery-NukulSharma** [substrate-developer-hub/substrate-front-end-template#181]
Hi, 

Sorry, i am newbie here. Going through substrate tutorial, where i have node template and front end template up and running.

However, i am unable to see any balance for test accounts, all operations are leading to failures. 

Refer image below, Can someone guide pls, what could be possible wrong here ?

![image](https://user-images.githubusercontent.com/67035862/122308965-0cc96280-cf2b-11eb-97f5-b3b55c7d51b5.png)

**Comment by NukeManDan** [comment]
What version of the node template are you using? I think this is a bug (really just a patch is needed on types) in the latest monthly release

**Comment by Kalanamith** [comment]
Please use the specified version on https://substrate.dev/docs/en/tutorials/build-a-dapp/front-end which is `v3.0.0` 
before running this version please empty your node cache `npm cache clean --force`

**Comment by NukeManDan** [comment]
Are you getting any errors in the browser logs?
Using the right flags to run the node in Dev mode?
`--dev`

**Comment by M4tsuri** [comment]
I have exactly the same problem. Also I got an error like this when trying to make a transaction.
<img width="1180" alt="Screen Shot 2021-07-11 at 16 26 17" src="https://user-images.githubusercontent.com/51822222/125187963-b9fe7480-e264-11eb-84d8-328980699510.png">
And I'm using the same version as mentioned in https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup.

**Comment by M4tsuri** [comment]
> I have exactly the same problem. Also I got an error like this when trying to make a transaction.
> <img alt="Screen Shot 2021-07-11 at 16 26 17" width="1180" src="https://user-images.githubusercontent.com/51822222/125187963-b9fe7480-e264-11eb-84d8-328980699510.png">
> And I'm using the same version as mentioned in https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup.

Solved. (But I don't know why)
For my situation, I run both this frontend and node on my server. I noticed it seems that this frontend does not connect to my own node by default (The configuration file under src/config specifies wss://dev-node.substrate.dev as the default provider). So I changed the configuration to make it connect to my own node. Now it works well. I think this problem is possibly caused by inconsistent version between the node on wss://dev-node.substrate.dev and the frontend.

**Comment by NukeManDan** [comment]
I think this is only set for running in docker, as we host a version of the node template to demo. Are you doing this?

 Cc @jimmychu0807 are you aware of how this demo is hosted & managed?

**Comment by Kalanamith** [comment]
This is working as long as you empty the node cache , reinstall everything as mentioned in the tutorial
