### ISSUE TITLE
Proof of existence tutorial front end template file upload section not appearing

### ISSUE THREAD

**Issue by Kalanamith** [substrate-developer-hub/substrate-front-end-template#182]
Steps 
* Follow the tutorial https://substrate.dev/docs/en/tutorials/build-a-dapp/front-end
* Proof of existence file upload section not appearing after modifying `TemplateModule.js` as mentioned in the tutorial

**Comment by NukeManDan** [comment]
Can you provide a https://stackoverflow.com/help/minimal-reproducible-example ?

There is also a solution branch for both the template repos to check against and try to see if its your build tools that are the issue (node, yarn, etc.)

https://github.com/substrate-developer-hub/substrate-node-template/tree/tutorials/solutions/build-a-dapp-v3+1

**Comment by Kalanamith** [comment]
Closing since its working

**Comment by Levike34** [comment]
It's not working. Followed the tutorial exactly and it does not load properly.

**Comment by MehranMazhar** [comment]
I have the same problem.
 Followed the tutorial exactly and it does not load properly.
Proof of existence file upload section not appearing after modifying TemplateModule.js as mentioned in the tutorial

**Comment by jimmychu0807** [comment]
will take a look

**Comment by omadoyeabraham** [comment]
@MehranMazhar You're welcome

I had the same "Create Claim" issue as well. The changes to fix that can be found here: https://github.com/teamchong/substrate-proof-of-existence-frontend/commit/ca16cf786ecf96bdb635286e14ea3344c9e24342

After that I believe everything else works fine.

**Comment by BruceChar** [comment]
> @omadoyeabraham Thank you for your help. useSubstrateState is not imported in the file . If we want to use useSubstrateState we have to importe first . I did this and again I got an error while running.
> 
> There is another useSubstrate at the end of the file which I changed to useSubstrateState where the project ran without error But when I upload a file and click the Create Claim button, it still gives an error. I think this project should be reviewed by its own developers

same here!

**Comment by jimmychu0807** [comment]
PR #241 should fix all issues mentioned here.

**Comment by MehranMazhar** [comment]
@jimmychu0807 
thanks
