### ISSUE TITLE
Application crash on invalid input params in pallet interactor

### ISSUE THREAD

**Issue by debris** [substrate-developer-hub/substrate-front-end-template#192]
version: 

```
v3.0.0+monthly-2021-05
```

steps to reproduce:

enter following data in the pallet interactor form and press `query`

<img width="610" alt="Screenshot 2021-08-12 at 16 35 33" src="https://user-images.githubusercontent.com/2613714/129216388-8037939d-69e1-4e39-be41-9db07ae9142a.png">

error:

<img width="1496" alt="Screenshot 2021-08-12 at 16 37 32" src="https://user-images.githubusercontent.com/2613714/129216525-271e0685-237e-4f44-820f-8c694944e57c.png">

**Comment by NukeManDan** [comment]
Remove the`0x` .
SS58 addresses are not hex prefixed or encoded: https://polkadot.js.org/docs/keyring/start/ss58/

**Comment by debris** [comment]
I know that removing `0x` helps, but imo the application should not crash on invalid input.
