### ISSUE TITLE
Transaction Failed: Error: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received

### ISSUE THREAD

**Issue by chusanchen** [substrate-developer-hub/substrate-front-end-template#196]
When I execute the program,  substrate-front-end-template   has some problems
My  substrate-front-end-template version is `substrate-front-end-template-master`
![ ](https://github.com/chusanchen/images/blob/main/image22/QQ%E6%88%AA%E5%9B%BE20210914190014.jpg)

and

![](https://github.com/chusanchen/images/blob/main/image22/wenti.jpg)

error information is 
`😞 Transaction Failed: Error: Unable to decode storage system.account: entry 0:: createType(AccountInfo):: {"nonce":"Index","consumers":"RefCount","providers":"RefCount","sufficients":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000001000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (72 bytes), created 0x0000000000000000000000000000001000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes)`

**Comment by jimmychu0807** [comment]
Close by #200
