### ISSUE TITLE
Update API to v6+ to support new v14 metadata

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-front-end-template#197]
https://github.com/substrate-developer-hub/substrate-front-end-template/blob/2bcedd13d6cfdcfb344847ade741e5a294d13fac/package.json#L18

*Breaking changes* to the upstream are about to be released, presently used on Rococo. API v6+ is required. To test before a formal release, we can connect to the public Rococo RPC node: `rococo-rpc.polkadot.io` (or spin up a `rococo-local` instance)

- [ ] A companion to this is needed to update to the node template

**Comment by jimmychu0807** [comment]
Close by #200
