### ISSUE TITLE
Submiting an extrinsic tx in sudo returns type error

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-front-end-template#202]
Submiting an extrinsic tx in sudo returns type error. The error in the console is long, something like

```
Uncaught Error: createType(Call):: Call: failed decoding sudo.sudo:: Struct: failed on args: 
{a big structure here}:: 
Cannot map Enum JSON, unable to find 'registry' in system, unused1, timestamp, unused3, grandpa,
balances, unused6, sudo, templatemodule, nicks
```

But the same error occurs in polkadot-js app also. This may require an upstream fix on polkadot-js api.

**Comment by NukeManDan** [comment]
https://github.com/polkadot-js/apps/issues/6222

**Comment by jimmychu0807** [comment]
Thanks Dan. Let me try later today.
