### ISSUE TITLE
More descriptive error handling than `{ "isTrusted": true }`

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-front-end-template#209]
https://github.com/paritytech/subport/issues/266 and many other get
```
Error Connecting to Substrate

{ "isTrusted": true }
```

And no other indication of what might be wrong. Most of the time this is due to simply not having remote connections allowed (the right default) but the vast majority of users are just experimenting with a development setup using this template. Some help to inform them of this common issue would useful!

**Comment by KevinRNelson** [comment]
If anyone is having this issue, I followed this tutorial and it fixed my issue: https://www.howtosolutions.net/2021/01/fixing-error-connecting-to-substrate-front-end-template-remote-clients/
