### ISSUE TITLE
can't get tx hash from signAndSend method when passing a handler into the function

### ISSUE THREAD

**Issue by anizeani** [substrate-developer-hub/substrate-front-end-template#217]
Hi, I was playing around with the TxButton component and I couldn't manage to get the TxHash from a transaction that is occuring when I pass to the signAndSend the txResHandler. 
It's about this part of the code: https://github.com/substrate-developer-hub/substrate-front-end-template/blob/main/src/substrate-lib/components/TxButton.js#L79-L82

So, I manage to get the txHash like this:
```
unsub = await txExecute.signAndSend(fromAcct); //(here I get back the txHash)
```
but when I pass a handler to the signAndSend:
```
unsub = await txExecute.signAndSend(fromAcct, txResHandler) //here unsub becomes a subscription.subscribe(), and I can't get the txHash from it, how should I get the txHash from a subscription.subscribe()? 
```
Yes, I read the polkadotjs documentation over and over, and I tried many things, but without succes. it's been hasseling me for ages. I would be super greatful if anybody could help me out here (more then just a referal to the polkadotjs documentation).

**Comment by jimmychu0807** [comment]
@anizeani It is documented here:
https://github.com/polkadot-js/docs/issues/159
