### ISSUE TITLE
Styling forced from substratecontextprovider

### ISSUE THREAD

**Issue by Brayn18** [substrate-developer-hub/substrate-front-end-template#234]
when exporting, substratecontextprovider, it makes all the website different styling. Is there any way to implement this api utilities in a react website done without changing style?

**Comment by jimmychu0807** [comment]
This worths a second look.

**Comment by jimmychu0807** [comment]
@Brayn18 I re-read the code. There are only two locations where we import css, one in the [`public/index.html`](https://github.com/substrate-developer-hub/substrate-front-end-template/blob/main/public/index.html#L24-L28) (this is only for the github forking banner), and another in [`src/App.js`](https://github.com/substrate-developer-hub/substrate-front-end-template/blob/main/src/App.js#L10). Could you confirm your styling change is not by accidentally importing these css (or other css) and using their relevant classes?

**Comment by NukeManDan** [comment]
Any updates here? I will close assuming this isn't relevant anymore.
