### ISSUE TITLE
Event Component: Warning: Encountered two children with the same key...

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-front-end-template#29]
The transfer component (and similar ones (eg [this one](https://github.com/JoshOrndorff/substrate-ui-template/blob/356ab2b47cfd22077e81db1b40c58e79a64ac35f/src/TemplateModule.jsx))) produce an error in the js console when submitting two ~~identical extrinsics~~ extrinsics with the same values.

Steps to reproduce
1. Clone repo, `yarn`, `yarn start`
2. Submit a transfer (eg Alice -> Bob 12345 tokens)
3. Observe the transaction completes successfully with no errors or warnings
4. Wait several blocks (this is not a nonce / `Priority is too low` issue)
5. Submit another transfer with the same sender, recipient, and amount
6. Observe the error in the console (but the transaction still succeeds and the tokens are transferred)
```
Warning: Encountered two children with the same key, `X Blocks Ago--balances:Transfer:: (phase={"ApplyExtrinsic":2})`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (created by Feed)
    in Feed (at Events.jsx:52)
    in div (created by GridColumn)
    in GridColumn (at Events.jsx:50)
    in Events (at App.jsx:118)
    in div (created by GridRow)
    in GridRow (at App.jsx:115)
    in div (created by Grid)
    in Grid (at App.jsx:101)
    in div (created by Container)
    in Container (at App.jsx:100)
    in App (at src/index.jsx:5)
```

Although the text says warning, it shows in the console as an error

**Comment by shawntabrizi** [comment]
This is actually from the events component. Basically every object in the "feed" needs a unique `key` value, but there is nothing to generate a key value from that I know of...

Probably a stackoverflow answer needed here

**Comment by JoshOrndorff** [comment]
I tried to give the events sequential keys on the `joshy-events-attempt` branch ([commit](https://github.com/substrate-developer-hub/substrate-ui-template/commit/aaa4b2df8a9c25e13da92016bf35633a4aa670ec)).

But for some reason the state variable never actually updates. The log shows
```
eventNumber is 1
n is 1
...
eventNumber is 1
n is 2
```

**Comment by shawntabrizi** [comment]
fixed with the commit above.
