### ISSUE TITLE
Events Component

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-front-end-template#3]
We should create an "Events" component which allows a user to see a history of events that fired on their node.

Maybe use a pop up notification, but I am more inclined to use a "feed" instead so it is easier to look back at the history.

**Comment by riusricardo** [comment]
I like the idea of events on a feed component. It will be easy to understand and useful for debugging.

**Comment by shawntabrizi** [comment]
Right now events are appearing in the console with the events module I wrote.

Will eventually update to make it appear in the UI, but for now, this is pretty satisfactory

**Comment by shawntabrizi** [comment]
Would be interested in having someone turn this into a Semantic UI thing rather than just browser console

**Comment by shawntabrizi** [comment]
Things are still a big wonky with the ordering, and how it looks, and adding block numbers, etc...

Really half bakes at the moment, but better than nothing I hope.

**Comment by shawntabrizi** [comment]
Needs #29 to be fixed

**Comment by shawntabrizi** [comment]
Fixed with the commit above.
