### ISSUE TITLE
Open UI on a different port

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-front-end-template#45]
I think a lot of different web app development things try to run a server on port 3000.

I think if we have a consistent, low conflict port number, it can help docs where we may link to the `localhost`.

I vote we use port 8000 which is what the `substrate-ui` project used.

**Comment by riusricardo** [comment]
I'm ok with this.

**Comment by JoshOrndorff** [comment]
Seems like low roi considering the script chooses the next available port if there is a conflict _and_ opens a browser tab for you. I wouldn't say no if someone wrote it though.

**Comment by shawntabrizi** [comment]
Yeah, my thought is about tutorials.
For example I have a link to `localhost:3000` in the tutorial. This link wont work if the web server does what you say. Small detail, but I think lower cost to change than to potentially have a problem like this
