### ISSUE TITLE
Improve Extrinsics component to support multiple params

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/substrate-front-end-template#48]
Currently the UI only supports a single input argument even though the runtime modules functions may expect a variable amount of arguments

**Comment by shawntabrizi** [comment]
This I think is too complicated for the front-end template.

The kind of UI that Jaco has for the Apps where the number of arguments change based on the expected input I think is quite a lot of work to enable.

Those components are meant to be pretty dead simple.

**Comment by ltfschoen** [comment]
The tutorial for this front-end template (which only supports a "single" argument) is tagged as "easy" at https://substrate.dev/en/tutorials, whilst the Substrate Collectables Workshop is also tagged as "easy", even though goes through setting up API endpoints that support "multiple" arguments using a oo7-based front-end. So maybe Substrate Collectables Workshop should be tagged as "medium" instead of "easy", otherwise it's too complicated for this "easy" front-end template?

If a developer is onboarded through the Substrate Collectables Workshop https://substrate.dev/en/tutorials where they create a oo7 front-end "template", and then they wants to build a front-end using the Polkadot.js API by using this template, then this template won't be plug-and-play because it doesn't allow them to call most of the endpoints, except for the ones that accept a single argument. i.e. they'll only be able to call the `createKitty` function, but not the `setPrice` or `transfer` functions.

Is this repo accepting PRs from the community for further improvement? Or is it just going to be archived once all it's currently opened issues are closed?

**Comment by JoshOrndorff** [comment]
I agree that reinventing the apps feature where parameter types are detected and fields generated is out of scope here.

I also think having this extrinsic component that only supports a small subset of extrinsics and doesn't make that clear is confusing and should be fixed. At minimum the component should be titled "one-parameter extrinsics".

**Comment by ltfschoen** [comment]
I was thinking you could just use this multiple selection instead of the parameter input field https://react.semantic-ui.com/modules/dropdown/#types-multiple-selection

In the template you could just include the Substrate Collectibles Workshop module `substratekitties`, then configure its supported functions in say /src/config/common.json so they appear in the drop-down list.

Then it offers an easy migration for DApp developers who want to try something different after doing the Substrate Collectibles Workshop, and if they want to add their own custom modules or functions they can either update that configuration file, or just enter a function as a tag, and if the tag isn't available it just shows them an error telling them they need to add that function to their runtime module.

**Comment by shawntabrizi** [comment]
@ltfschoen you completely misunderstand what the abilities of the front end template is.

You can absolutely make your own component making a transaction which supports multiple inputs.

Furthermore front end development and runtime development are not measured on the same "scale". Building a runtime will always be way way more complicated than building a front end. The point of the level system is to say which kind of user can approach the tutorial. In the case of kitties, anyone should be able to do it, and thus it is easy.

> titled "one-parameter extrinsics".

Unfortunately this is not true either cause you could pass a pre-encoded multi parameter value and I think it would work just fine.

**Comment by ltfschoen** [comment]
@shawntabrizi Ok, we'll the only thing that I don't understand is why the spread operator isn't splitting the given array into a list of comma separated values to be used as function parameters of `tx` here https://github.com/substrate-developer-hub/substrate-front-end-template/pull/49#issuecomment-536352623,

**Comment by ltfschoen** [comment]
@shawntabrizi FYI, it works if I convert it into a comma separated list and then back into an array before using the spread operator:
```
let sillySpread = params.join(",").split(",");
txExecute = tx(...sillySpread);
```

**Comment by shawntabrizi** [comment]
when you pass a value through the input UX, it goes in as a text string. Then you pass it to `[params]` where it becomes a single array with a string in it.

So the spread operator is only acting on a single string.

Of course if you parse the string manually, you will get a behavior you are looking for (note that your code snippet does not do anything with `join(",")`).

The solution here is to have a small check here which will either parse valid array input if possible, or a string if not.
