### ISSUE TITLE
Setting up circleci

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-front-end-template#52]
@shawntabrizi 

I believe I need your permission to initialize this project to use cicleCI

![Screen Shot 2019-10-01 at 2 21 33 PM](https://user-images.githubusercontent.com/898091/65939026-3c82bf00-e457-11e9-86bb-34e6eb9df3fc.png)

**Comment by shawntabrizi** [comment]
Okay, it should be live on CircleCi now, you just need to upload a `yaml` file to `.circleci` folder

**Comment by jimmychu0807** [comment]
@shawntabrizi wow, having fun playing with circleCI this evening... It now run test on all branch pushes except `gh-pages` and automatically deploy upon pushing to `master`.

**Comment by JoshOrndorff** [comment]
I'd like to setup branch protections so we can't merge PRs into master without passing linting. What does everyone think?

**Comment by JoshOrndorff** [comment]
Branch protections are in place.
