### ISSUE TITLE
Linting is too agressive for a template

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-front-end-template#54]
Recently @jimmychu0807 [got eslint working](https://github.com/substrate-developer-hub/substrate-front-end-template/pull/51). This change brought several distinct advantages, but also some disadvantages.

**Advantages**
* When reviewing PRs, we will see only relevant logic changes, not formatting changes
* PRs will not conflict with one another because of personal stylistic preferences
* Arbitrary style choices will not be made and unmade depending who touched the code last.

**Disadvantages**
* New users who may not know or care about our style conventions may be told their code doesn't compile
* Working code copied from other sources may need to be adjusted according to our linting stnadards

**Possible Solutions**
* Reduce stylistic linting problems to warnings rather than errors
* Enforce that linting passes in CI (so we can't merge stuff that doesn't lint) but don't display linting errors on `yarn start`
* Remove linting entirely -- pretty extreme, but it is an option.

**Comment by jimmychu0807** [comment]
Let me update so linting issues become warnings instead of errors.

**Comment by jimmychu0807** [comment]
Addressed with this [code push](https://github.com/substrate-developer-hub/substrate-front-end-template/commit/aab214c06fdfc9fc6e842135e790c5a9a9c051d0). 

Run `yarn install` after fetching from git.
