### ISSUE TITLE
Publishing substrate-lib components as a separate npm package?

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-front-end-template#66]
After:
1. completing a socket selection function/component, 
2. putting `AccountSelector` component into `src/substrate-lib/components`,
3. adding a few test cases (not comprehensive),
4. adding an `examples` folder, copying some of current component in `src/` as demo on how to use it

I would like to publish this as a separate npm package. So in future app developers don't have to keep forking from our front-end template, but can just use it as `yarn add ...`. Also address Julien issue that need to keep a separate fork after adding his own functionalities.

What's your thought?

Probably called `substrate-react`.

**Comment by jimmychu0807** [comment]
@shawntabrizi feedback copied here for reference

> we should think about the long term maintainence required here. Does it make sense for a package like this to be included with the Polkadot-JS stuff? As in, rather than making another library which ultimately depends on Polkadot-JS, we include it with the Polkadot-JS ecosystem and have them maintain it in the future?
>
> We really should evalute the value add here. The point of the Substrate UI is not necessarily to provide a set of libraries for the user, but just to show them how things can be done. The libraries at the end of the day are the Polkadot JS API stuff
>
> I don't expect many people to actually build their final front end using the front-end template, rather it will be the first starting point for tutorials or for people to hack on, and a great way to reference how to do X.

**Comment by jimmychu0807** [comment]
thought: replace `substrate-ui-new` with front-end-template?

**Comment by shawntabrizi** [comment]
> thought: replace the result of substrate-ui-new with front-end-template?

@jimmychu0807 there is already a PR for this: https://github.com/paritytech/substrate-up/pull/39/files

Waiting for us to move to the new version of the docs to merge it as it will break a lot of our initial setup instructions
