### ISSUE TITLE
Better error handling on invalid custom type

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-front-end-template#73]
Front end can display an error message showing invalid custom type, as opposed to hanging on the loading screen.

**Comment by JoshOrndorff** [comment]
Is this fixed?

**Comment by jimmychu0807** [comment]
It does now 😄 

![Screenshot 2020-06-07 at 21 09 13](https://user-images.githubusercontent.com/898091/83969621-96e7ef80-a903-11ea-9138-6c488cfca4ca.png)
