### ISSUE TITLE
UI stays active when node dies

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-front-end-template#76]
When the node to which the UI is connected dies, the UI should return to the "Connecting to the blockchain" spinner screen. Currently the UI remains active.

**Comment by ltfschoen** [comment]
Is the addendum to this Substrate Seminar ready to publish? https://youtu.be/hhl14Xlbhlw?t=5687

**Comment by JoshOrndorff** [comment]
@ltfschoen The addendum is in the very same video. It starts at 136:18. In fact I was recording it when I opened this issue.
