### ISSUE TITLE
react-scripts: not found

### ISSUE THREAD

**Issue by drandreaskrueger** [substrate-developer-hub/substrate-front-end-template#77]
```
git clone https://github.com/substrate-developer-hub/substrate-front-end-template.git
cd substrate-front-end-template/
yarn start / yarn build
```
yarn run v1.19.1   
$ PORT=8000 react-scripts start   
/bin/sh: 1: react-scripts: not found   
error Command failed with exit code 127.   
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by drandreaskrueger** [comment]
npm i -g react-scripts

**Comment by JoshOrndorff** [comment]
You forgot to run `yarn install` as recommended in the readme
https://github.com/substrate-developer-hub/substrate-front-end-template/blob/master/README.md#installation

**Comment by drandreaskrueger** [comment]
ooops
