### ISSUE TITLE
Automatically connect to the best node possible (Connection Component)

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-front-end-template#9]
The UI should try to automatically connect to the best node possible.

In order of priority:

* Local Node (`ws://127.0.0.1:9944/`)
* Dev Node (`wss://dev-node.substrate.dev:9944/`)
* Kusama Node
* Custom Node (input field)
* Other?

There should also be a component which allow you to set the node you want to connect to

**Comment by jimmychu0807** [comment]
Also allow programmatically to switch socket URL

**Comment by jimmychu0807** [comment]
We can provide an `rpc` param to specify a node in the URL now. This should give enough flexibility. Closing this issue for now.
