### ISSUE TITLE
Frontend-template extension

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-front-end-template#91]
This ticket is to keep track of a list of tasks on front-end template extension so that devhub tutorial/doc can refer to using this template instead of polkadot-js app when we need front-end interaction. 

This is because we have less control on polkadot-js app which may break integrating with Substrate node-template once in a while. We also gain better version control on which node- & front-end template work together.

### Extrinsics, after picking on a pallet and extrinsic function call:
- [x] detect # of params and each param type
- [x] allow submitting options (something in signedExtra)
- [x] allow option of sudo
- [x] allow option of submitting with signed or unsigned

### Chain State
- [x] allow query of pallet constants also
- [x] after choosing pallet storage, detect # of input options needed and determine each param type. Sometimes this could be 0. Now are have hard-coded to send one option out.

**Comment by danforbes** [comment]
In the tutorial to start a private network we use the RPC capabilities from the Toolbox app to insert a key - can we do this using the front-end template?

**Comment by jimmychu0807** [comment]
> In the tutorial to start a private network we use the RPC capabilities from the Toolbox app to insert a key - can we do this using the front-end template?

I will open another ticket to explore about RPC capability from front-end template.
