### ISSUE TITLE
Allow decorating RPC information in the UI config

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-front-end-template#97]

**Comment by JoshOrndorff** [comment]
https://polkadot.js.org/api/start/rpc.custom.html

**Comment by danforbes** [comment]
Is this what is preventing users from submitting parameters along with RPC calls?

![image](https://user-images.githubusercontent.com/2193247/83255343-18ea5280-a165-11ea-8481-a1b4f04ac668.png)

**Comment by JoshOrndorff** [comment]
> Is this what is preventing users from submitting parameters along with RPC calls?

No this issue is about allowing the polkadot js api instance, and thus the front end, to know about custom RPC endpoints. That is, RPC endpoints that are added specifically for this chain and not included with Substrate.
